---
title: "Mediator_Toy"
author: "Pin"
date: "2025-12-30"
output: html_document
---

```{r, include=FALSE}
library(mediation)
library(sandwich)
library(dplyr)
library(readxl)
library(stargazer)
library(psych)
library(CMAverse)
knitr::opts_chunk$set(warning = FALSE)
```

```{r Read Data}
Toy <- read_excel("LDL_Toy_Data.xlsx", sheet = "INSTANCE1")
Toy <- Toy %>%
  mutate(DM = as.factor(cut(GLU,
                  breaks = c(0,100,500),
                  labels = c("FALSE","TRUE"))),
         HPL = as.factor(cut(LDL,
                   breaks = c(0,110,500),
                   labels = c("FALSE","TRUE"))),
         HTN = as.factor(cut(BP,
                   breaks = c(0,140,500),
                   labels = c("FALSE","TRUE"))),
         Statin = as.factor(Statin),
         Dog = as.factor(Dog),
         GeneS = as.factor(GeneS),
         GeneA = as.factor(GeneA),
         
         StatY = Age - 25)
Toy$StatY[Toy$StatY<0] <- 0
Toy$StatY[Toy$Statin==FALSE] <- 0
head(Toy)
```

```{r Fit Models}
med = lm(LDL ~ Statin + BMI + Dog, data = Toy)
add = glm(DM ~ LDL + Statin + Statin * LDL + BMI + Dog, data = Toy, family = "binomial")
```

```{r Fit Mediation}
fitMed <- mediation::mediate(med, add, treat = "Statin", mediator = "LDL")
summary(fitMed)
```

```{r Plot Mediation}
plot(fitMed)
```

```{r, include=FALSE}
est <- cmest(data = Toy, model = "rb", outcome = "DM", exposure = "Statin", mediator = c("LDL"), basec = c("BMI","Dog"), EMint = TRUE, mreg = list("linear"), yreg = "logistic", astar = "FALSE", a = "TRUE", mval = list(1), estimation = "imputation", inference = "bootstrap", nboot = 1000)
```

```{r Plot New Mediation}
summary(est)
ggcmest(est) + 
  ggplot2::scale_y_log10() +
  ggplot2::theme(axis.text.x = ggplot2 ::element_text(angle = 30, vjust = 0.8)) 
```

